### PR TITLE
Fix Alerts

### LINKED ISSUE #188: Alerts do not clear drawn routes when closing pane
https://github.com/user-attachments/assets/d516cbf2-b225-408c-8ab5-5c29235604bb

### PR DESCRIPTION
**Pull request by PalaashPandey**
## Describe your changes
Alerts should now make all routes inactive (but show which routes are affected) when clicked and re-activate the route previously selected when closing AlertDetails

## Issue number and link
#188: https://github.com/Maroon-Rides/MaroonRides/issues/188

### CODE REVIEW

File: app/components/map/MapView.tsx
Comment (bwees) [inline app/components/map/MapView.tsx:1]: we really need to add a linter to this project :/

File: app/components/sheets/AlertList.tsx [hunk 1]
```diff
@@ -1,4 +1,4 @@
-import React, { memo, useEffect, useState } from "react";
+import React, { memo, useEffect, useState, useRef } from "react";
```
Comment (bwees) [inline app/components/sheets/AlertList.tsx]: can you delete `useRef` from here so tsc passes?

File: app/components/sheets/AlertList.tsx [hunk 2]
```diff
@@ -106,6 +112,10 @@ const AlertList: React.FC<SheetProps> = ({ sheetRef }) => {
                     return (
                         <TouchableOpacity
                             onPress={() => {
+                                const selectedRouteCopy = JSON.stringify(selectedRoute);
```
Comment (bwees) [inline app/components/sheets/AlertList.tsx]: can we make oldSelectedRoute be of type IMapRoute instead of stringifying to JSON and back? Stringifying and parsing is extremely heavy (especially on the size of object that IMapRoute is).

File: app/data/app_state.ts [hunk 3]
```diff
@@ -16,6 +16,9 @@ interface AppState {
     selectedRouteDirection: string | null,
     setSelectedRouteDirection: (selectedRouteDirection: string | null) => void,
 
+    oldSelectedRoute: string | null,
+    setOldSelectedRoute: (oldSelectedRouteDirection: string | null) => void,
```
Comment (bwees) [inline app/data/app_state.ts]: Update your type from a string to IMapRoute

**Review by bwees — CHANGES_REQUESTED** [review]

**Review by bwees — APPROVED** [review]
